---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitea
  labels:
    id: prod000001
    app: gitea
    type: ceph-rbd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  selector:
    matchLabels:
      id: prod000001
      app: gitea
      type: ceph-rbd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitea-mysql
  labels:
    id: prod000002
    app: gitea
    type: ceph-rbd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  selector:
    matchLabels:
      id: prod000002
      app: gitea
      type: ceph-rbd