---
kind: ConfigMap
apiVersion: v1
metadata:
  name: gitea-config
  labels:
    app: gitea
    type: config
data:
  app.ini: |-
    APP_NAME = Avamar Git Repo
    RUN_MODE = prod

    [server]
    PROTOCOL  = https
    ROOT_URL  = https://git.datadomain.com:443/
    HTTP_PORT = 443
    CERT_FILE = /certs/gitea.pem
    KEY_FILE  = /certs/gitea-key.pem
    ; Enables git-lfs support. true or false, default is false.
    LFS_START_SERVER = true
    ; Where your lfs files reside, default is data/lfs.
    LFS_CONTENT_PATH = /data/lfs

    [mailer]
    ENABLED       = true
    FROM          = git@emc.com
    MAILER_TYPE   = sendmail
    SENDMAIL_PATH = /usr/sbin/sendmail

    [oauth2]
    JWT_SECRET = g2dqHeyWsLkjXyDENMgu5GkrCqbL9fQ3WKhXbUB1E3w

    [security]
    INSTALL_LOCK   = true
    SECRET_KEY     =
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MDc1OTQwODF9.t64RpqhLlRY2O4zdU5iJSHt4EO_W2QgfMYCl-RvTOss
