---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  rules:
  - host: dash.datadomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tekton-dashboard
          servicePort: 9098
