#kubectl create secret docker-registry hub-user-robot \
#--docker-server=<your-registry-server> \
#--docker-username=<your-name> \
#--docker-password=<your-pword> \
#--docker-email=<your-email>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-user-robot
secrets:
  - name: hub-secret-robot
