---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-p4-workspace
  namespace: ops
  labels:
    id: prod000012
    app: perforce
    storage: cephfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Gi
  selector:
    matchLabels:
      id: prod000012
      app: perforce
      storage: cephfs
